apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: authserver-in-memorykube
          image: amberex/authserver_in_memorykube
          ports:
            - containerPort: 8080
