apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interfacekube
          image: amberex/user_interfacekube
          ports:
            - containerPort: 8080
